# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20160501_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='cod',
            field=models.CharField(max_length=6),
        ),
    ]
